// add_offset :: (rect : Rectangle, offset : float) -> Rectangle {
// 	return .{
// 		x + offset,
// 		y + offset,
// 		width - offset,
// 		height - offset		
// 	};
// }
// ui_base :: (rect : Rectangle, border := 2.) {
// 	DrawRectangleRec(rect, GRAY);
// 	DrawRectangleRec(add_offset(rect, border), RAYWHITE);
// }

// ui_text :: (rect : Rectangle, text : string) {

// }

// ui_draw :: () {

// }
// ui_init :: () {

// }
// ui_deinit :: () {

// }